### PR TITLE
Features/dont break on errors

### PR DESCRIPTION
**Pull request by cr0cK**
We could want to be only notified on vulnerabilities without breaking the Gulp process.
I suggest a dict as the first argument that allows this features.

### CODE REVIEW

**Comment by joeycozza** [comment]
Thanks. That is a great feature I didn't think of.

**Comment by cr0cK** [comment]
Thanks you for your reactivity!
Could you publish a new version to npm?

**Comment by joeycozza** [comment]
I'm fixing an issue real quick.  If there were no vulnerabilities found, nothing is returned. I should have fixed it, just running tests real quick. Give me about 15 minutes and I should be able to publish to npm.

**Comment by joeycozza** [comment]
Okay, that should be published and good to go now.  Thanks again for your help!

**Comment by cr0cK** [comment]
You're welcome :)

**Pull request merged**
